FROM apache/airflow:2.5.0

USER root
RUN apt-get update \
    && apt-get install -y gnupg2 wget

#installing firefox-esr
RUN apt install -y firefox-esr
RUN chmod +x /usr/bin/firefox-esr

#installing geckodriver
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
RUN tar -xzvf geckodriver-v0.32.0-linux64.tar.gz -C /usr/local/bin
RUN chmod +x /usr/local/bin/geckodriver

RUN mkdir -p /.cache \
    && chmod 777 /.cache 

#installing python requirements
USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --user --upgrade pip \
    && pip cache purge \
    && pip install --user --no-cache-dir -r /requirements.txt